<?php

return [
    'default' => [
        'mailchimp' => t('Because it sends data to %s.', 'MailChimp'),
        'd3_mailchimp' => t('Because it sends data to %s.', 'MailChimp'),
        'mail-service-integration' => t('Because it sends data to %s.', t('various mail services.')),
        'formify' => t('Because forms can contain personal information.'),
        'formidable-lite' => t('Because forms can contain personal information.'),
        'formidable-full-version' => t('Because forms can contain personal information.'),
        'form-plus1' => t('Because it sends data to %s.', 'MailChimp'),
        'wufoo-forms1' => t('Because it sends data to %s.', 'Wufoo'),
        'live-chat' => t('Because it sends data to %s.', 'Tawk.to'),
        'ecommerce-with-snipcart' => t('Because it sends data to %s.', 'snipcart.com'),
        'like-this' => t('Because it uses the Facebook plugin to share and like.'),
        'share-me' => t('Because it uses social media plugins to share and like.'),
        'community_store' => t('Because it stores orders and customer data.'),
        'bitter-shop-system' => t('Because it stores orders and customer data.'),
        'contact-form-no-links1' => t('Because it sends the email to an email address.'),
        'centry' => t('Because it might send logs to another server. (configurable)'),
        'image-optimizer' => t('Because it might send images to %s. (configurable)', 'TinyPNG'),
        'storage-for-amazon-s3' => t('Because it sends data to %s.', 'Amazon'),
        'likes-this-block' => t('Because it stores the user id.'),
        'chatwee-chat' => t('Because it sends data to %s.', 'Chatwee'),
        'zopim-chat-3rd-party' => t('Because it sends data to %s.', 'Zopim'),
        'slife' => t('Because it sends data to %s.', 'Slack'),
        'mautic' => t('Because it sends data to %s.', 'Mautic'),
        'bugsnag' => t('Because it sends data to %s.', 'Bugsnag'),
        's3_storage' => t('Because it sends data to %s.', 'Amazon S3'),
        'auto_login' => t('Because auto login is probably bad for security.'),
        'mollie_plugin' => t('Because it sends data to %s.', 'Mollie'),
        'mollie' => t('Because it sends data to %s.', 'Mollie'),
        'ec_recaptcha' => t('Because it loads external code from %s.', 'Google'),
        'msv_location_map' => t('Because it loads external code from %s.', 'Google'),
        'hw_store_location' => t('Because it loads external code from %s.', 'Google'),
        'blog_comments' => t('Because it stores user data.'),
    ],
];
